### ISSUE TITLE
README.md build status link is not valid

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/mbed-webapp-example#7]
## Development

[![Build Status](https://magnum.travis-ci.com/ARMmbed/mbed-webapp-example.svg?token=dwQ5RVGhwvjYBMfR1k6t&branch=master)](https://magnum.travis-ci.com/ARMmbed/mbed-webapp-example)

-> broken link.

**Comment by szysas** [comment]
removed broken link
